services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: acmedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - acme_pg:/var/lib/postgresql/data

volumes:
  acme_pg:
